# Proyek Analisis Data: Air Quality Dataset
- **Nama:** Auliasari Citra S
- **Email:**  citrasyamsuraa@gmail.com
- **ID Dicoding:** auliasarics

## Menentukan Pertanyaan Bisnis

- Bagaimana tren kualitas udara (PM2.5, PM10, SO2, NO2, CO, O3) di berbagai stasiun pengukuran sepanjang tahun?
- Bagaimana hubungan antara kondisi cuaca (suhu, tekanan udara, kelembaban, hujan, arah dan kecepatan angin) dengan kualitas udara?
- Bagaimana perbandingan kualitas udara antar stasiun pada waktu tertentu?

## Import Semua Packages/Library yang Digunakan

In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Data Wrangling

### Gathering Data

In [14]:
aotizhongxin_df = pd.read_csv("https://raw.githubusercontent.com/auliasarics/Proyek-Data-Analisis-dengan-Python/refs/heads/main/data/PRSA_Data_Aotizhongxin_20130301-20170228.csv")
aotizhongxin_df.head()

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,wd,WSPM,station
0,1,2013,3,1,0,4.0,4.0,4.0,7.0,300.0,77.0,-0.7,1023.0,-18.8,0.0,NNW,4.4,Aotizhongxin
1,2,2013,3,1,1,8.0,8.0,4.0,7.0,300.0,77.0,-1.1,1023.2,-18.2,0.0,N,4.7,Aotizhongxin
2,3,2013,3,1,2,7.0,7.0,5.0,10.0,300.0,73.0,-1.1,1023.5,-18.2,0.0,NNW,5.6,Aotizhongxin
3,4,2013,3,1,3,6.0,6.0,11.0,11.0,300.0,72.0,-1.4,1024.5,-19.4,0.0,NW,3.1,Aotizhongxin
4,5,2013,3,1,4,3.0,3.0,12.0,12.0,300.0,72.0,-2.0,1025.2,-19.5,0.0,N,2.0,Aotizhongxin

In [15]:
changping_df =pd.read_csv("https://raw.githubusercontent.com/auliasarics/Proyek-Data-Analisis-dengan-Python/refs/heads/main/data/PRSA_Data_Changping_20130301-20170228.csv")
changping_df.head()

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,wd,WSPM,station
0,1,2013,3,1,0,3.0,6.0,13.0,7.0,300.0,85.0,-2.3,1020.8,-19.7,0.0,E,0.5,Changping
1,2,2013,3,1,1,3.0,3.0,6.0,6.0,300.0,85.0,-2.5,1021.3,-19.0,0.0,ENE,0.7,Changping
2,3,2013,3,1,2,3.0,3.0,22.0,13.0,400.0,74.0,-3.0,1021.3,-19.9,0.0,ENE,0.2,Changping
3,4,2013,3,1,3,3.0,6.0,12.0,8.0,300.0,81.0,-3.6,1021.8,-19.1,0.0,NNE,1.0,Changping
4,5,2013,3,1,4,3.0,3.0,14.0,8.0,300.0,81.0,-3.5,1022.3,-19.4,0.0,N,2.1,Changping

In [16]:
dingling_df=pd.read_csv("https://raw.githubusercontent.com/auliasarics/Proyek-Data-Analisis-dengan-Python/refs/heads/main/data/PRSA_Data_Dingling_20130301-20170228.csv")
dingling_df.head()

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,wd,WSPM,station
0,1,2013,3,1,0,4.0,4.0,3.0,NaN,200.0,82.0,-2.3,1020.8,-19.7,0.0,E,0.5,Dingling
1,2,2013,3,1,1,7.0,7.0,3.0,NaN,200.0,80.0,-2.5,1021.3,-19.0,0.0,ENE,0.7,Dingling
2,3,2013,3,1,2,5.0,5.0,3.0,2.0,200.0,79.0,-3.0,1021.3,-19.9,0.0,ENE,0.2,Dingling
3,4,2013,3,1,3,6.0,6.0,3.0,NaN,200.0,79.0,-3.6,1021.8,-19.1,0.0,NNE,1.0,Dingling
4,5,2013,3,1,4,5.0,5.0,3.0,NaN,200.0,81.0,-3.5,1022.3,-19.4,0.0,N,2.1,Dingling

In [17]:
dongsi_df=pd.read_csv("https://raw.githubusercontent.com/auliasarics/Proyek-Data-Analisis-dengan-Python/refs/heads/main/data/PRSA_Data_Dongsi_20130301-20170228.csv")
dongsi_df.head()

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,wd,WSPM,station
0,1,2013,3,1,0,9.0,9.0,3.0,17.0,300.0,89.0,-0.5,1024.5,-21.4,0.0,NNW,5.7,Dongsi
1,2,2013,3,1,1,4.0,4.0,3.0,16.0,300.0,88.0,-0.7,1025.1,-22.1,0.0,NW,3.9,Dongsi
2,3,2013,3,1,2,7.0,7.0,NaN,17.0,300.0,60.0,-1.2,1025.3,-24.6,0.0,NNW,5.3,Dongsi
3,4,2013,3,1,3,3.0,3.0,5.0,18.0,NaN,NaN,-1.4,1026.2,-25.5,0.0,N,4.9,Dongsi
4,5,2013,3,1,4,3.0,3.0,7.0,NaN,200.0,84.0,-1.9,1027.1,-24.5,0.0,NNW,3.2,Dongsi

In [18]:
guanyuan_df=pd.read_csv("https://raw.githubusercontent.com/auliasarics/Proyek-Data-Analisis-dengan-Python/refs/heads/main/data/PRSA_Data_Guanyuan_20130301-20170228.csv")
guanyuan_df.head()

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,wd,WSPM,station
0,1,2013,3,1,0,4.0,4.0,14.0,20.0,300.0,69.0,-0.7,1023.0,-18.8,0.0,NNW,4.4,Guanyuan
1,2,2013,3,1,1,4.0,4.0,13.0,17.0,300.0,72.0,-1.1,1023.2,-18.2,0.0,N,4.7,Guanyuan
2,3,2013,3,1,2,3.0,3.0,10.0,19.0,300.0,69.0,-1.1,1023.5,-18.2,0.0,NNW,5.6,Guanyuan
3,4,2013,3,1,3,3.0,6.0,7.0,24.0,400.0,62.0,-1.4,1024.5,-19.4,0.0,NW,3.1,Guanyuan
4,5,2013,3,1,4,3.0,6.0,5.0,14.0,400.0,71.0,-2.0,1025.2,-19.5,0.0,N,2.0,Guanyuan

In [19]:
gucheng_df=pd.read_csv("https://raw.githubusercontent.com/auliasarics/Proyek-Data-Analisis-dengan-Python/refs/heads/main/data/PRSA_Data_Gucheng_20130301-20170228.csv")
gucheng_df.head()

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,wd,WSPM,station
0,1,2013,3,1,0,6.0,18.0,5.0,NaN,800.0,88.0,0.1,1021.1,-18.6,0.0,NW,4.4,Gucheng
1,2,2013,3,1,1,6.0,15.0,5.0,NaN,800.0,88.0,-0.3,1021.5,-19.0,0.0,NW,4.0,Gucheng
2,3,2013,3,1,2,5.0,18.0,NaN,NaN,700.0,52.0,-0.7,1021.5,-19.8,0.0,WNW,4.6,Gucheng
3,4,2013,3,1,3,6.0,20.0,6.0,NaN,NaN,NaN,-1.0,1022.7,-21.2,0.0,W,2.8,Gucheng
4,5,2013,3,1,4,5.0,17.0,5.0,NaN,600.0,73.0,-1.3,1023.0,-21.4,0.0,WNW,3.6,Gucheng

In [20]:
huairou_df=pd.read_csv("https://raw.githubusercontent.com/auliasarics/Proyek-Data-Analisis-dengan-Python/refs/heads/main/data/PRSA_Data_Huairou_20130301-20170228.csv")
huairou_df.head()

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,wd,WSPM,station
0,1,2013,3,1,0,7.0,7.0,3.0,2.0,100.0,91.0,-2.3,1020.3,-20.7,0.0,WNW,3.1,Huairou
1,2,2013,3,1,1,4.0,4.0,3.0,NaN,100.0,92.0,-2.7,1020.8,-20.5,0.0,NNW,1.5,Huairou
2,3,2013,3,1,2,4.0,4.0,NaN,NaN,100.0,91.0,-3.2,1020.6,-21.4,0.0,NW,1.8,Huairou
3,4,2013,3,1,3,3.0,3.0,3.0,2.0,NaN,NaN,-3.3,1021.3,-23.7,0.0,NNW,2.4,Huairou
4,5,2013,3,1,4,3.0,3.0,7.0,NaN,300.0,86.0,-4.1,1022.1,-22.7,0.0,NNW,2.2,Huairou

In [ ]:
nongzhanguan_df=pd.read_csv("https://raw.githubusercontent.com/auliasarics/Proyek-Data-Analisis-dengan-Python/refs/heads/main/data/PRSA_Data_Nongzhanguan_20130301-20170228.csv")
nongzhanguan_df.head()

In [ ]:
shunyi_df=pd.read_csv("https://raw.githubusercontent.com/auliasarics/Proyek-Data-Analisis-dengan-Python/refs/heads/main/data/PRSA_Data_Shunyi_20130301-20170228.csv")
shunyi_df.head()

In [ ]:
tiantan_df=pd.read_csv("https://raw.githubusercontent.com/auliasarics/Proyek-Data-Analisis-dengan-Python/refs/heads/main/data/PRSA_Data_Tiantan_20130301-20170228.csv")
tiantan_df.head()

In [ ]:
wanliu_df=pd.read_csv("https://raw.githubusercontent.com/auliasarics/Proyek-Data-Analisis-dengan-Python/refs/heads/main/data/PRSA_Data_Wanliu_20130301-20170228.csv")
wanliu_df.head()

In [ ]:
wanshouxigong_df=pd.read_csv("https://raw.githubusercontent.com/auliasarics/Proyek-Data-Analisis-dengan-Python/refs/heads/main/data/PRSA_Data_Wanshouxigong_20130301-20170228.csv")
wanshouxigong_df.head()

**Insight:**
- Terdapat 12 data set, yang masing-masing data menggambarkan kualitas air pada 12 stasiun yang berbeda
- Setiap data set terdiri dari kolom tahun, bulan, hari, PM2.5, PM10, SO2, NO2, CO, O3, temperatur, tekanan, DEWP, curah hujan, wd, WSPM, dan nama stasiun

### Assessing Data

In [ ]:
aotizhongxin_df.info()
aotizhongxin_df.isna().sum()
print("Jumlah duplikasi: ", aotizhongxin_df.duplicated().sum())
aotizhongxin_df.describe()

In [ ]:
changping_df.info()
changping_df.isna().sum()
print("Jumlah duplikasi: ", changping_df.duplicated().sum())
changping_df.describe()

In [ ]:
dingling_df.info()
dingling_df.isna().sum()
print("Jumlah duplikasi: ", dingling_df.duplicated().sum())
dingling_df.describe()

In [ ]:
dongsi_df.info()
dongsi_df.isna().sum()
print("Jumlah duplikasi: ", dongsi_df.duplicated().sum())
dongsi_df.describe()

In [ ]:
guanyuan_df.info()
guanyuan_df.isna().sum()
print("Jumlah duplikasi: ", guanyuan_df.duplicated().sum())
guanyuan_df.describe()

In [ ]:
gucheng_df.info()
gucheng_df.isna().sum()
print("Jumlah duplikasi: ", gucheng_df.duplicated().sum())
gucheng_df.describe()

In [ ]:
huairou_df.info()
huairou_df.isna().sum()
print("Jumlah duplikasi: ", huairou_df.duplicated().sum())
huairou_df.describe()

In [ ]:
nongzhanguan_df.info()
nongzhanguan_df.isna().sum()
print("Jumlah duplikasi: ", nongzhanguan_df.duplicated().sum())
nongzhanguan_df.describe()

In [ ]:
shunyi_df.info()
shunyi_df.isna().sum()
print("Jumlah duplikasi: ", shunyi_df.duplicated().sum())
shunyi_df.describe()

In [ ]:
tiantan_df.info()
tiantan_df.isna().sum()
print("Jumlah duplikasi: ", tiantan_df.duplicated().sum())
tiantan_df.describe()

In [ ]:
wanliu_df.info()
wanliu_df.isna().sum()
print("Jumlah duplikasi: ", wanliu_df.duplicated().sum())
wanliu_df.describe()

In [ ]:
wanshouxigong_df.info()
wanshouxigong_df.isna().sum()
print("Jumlah duplikasi: ", wanshouxigong_df.duplicated().sum())
wanshouxigong_df.describe()

**Insight:**
- Terdapat missing value pada kolom PM2.5, PM10, SO2, NO2, CO, O3, TEMP, PRES, DEWP, wd, RAIN, WSPM
- Serta terdapat inaccurate value

### Cleaning Data

In [ ]:
dataframes = [
    aotizhongxin_df, changping_df, dingling_df, dongsi_df, guanyuan_df, gucheng_df, huairou_df,
    nongzhanguan_df, shunyi_df, tiantan_df, wanliu_df, wanshouxigong_df
]

def clean_missing_values(dfs):
    for df in dfs:
        numeric_columns = df.select_dtypes(include=['number']).columns.difference(['No'])
        for column in numeric_columns:
            if df[column].isna().any():
                df[column] = df[column].fillna(df[column].median())

        if 'wd' in df.columns and df['wd'].isna().any():
            df['wd'] = df['wd'].ffill()

if __name__ == "__main__":
    clean_missing_values(dataframes)

In [ ]:
null_counts = {}

for i, df in enumerate(dataframes):
    if not df.empty:
        df_name = f"DataFrame_{i+1}"  
        null_counts[df_name] = df.isna().sum()

if null_counts:
    print(pd.DataFrame(null_counts).transpose())
else:
    print("Tidak ada nilai yang hilang dalam DataFrame yang diproses.")

**Insight:**
- nilai yang hilang pada kolom numerik diimputasi menggunakan median untuk menjaga kualitas data dan hasil analisis yang lebih reliabel
- sedangkan kolom kategorikal seperti wd, menggunakan metode forward fill untuk menjaga kontinuitas data dan menghindari pengisian nilai yang tidak sesuai

## Exploratory Data Analysis (EDA)

### Explore ...

In [ ]:
# Menggabungkan seluruh DataFrame dalam list menjadi satu DataFrame
combined_df = pd.concat(dataframes, keys=range(len(dataframes)))
combined_df.reset_index(inplace=True)

print(combined_df)

In [ ]:
# Mengeksplorasi seluruh data
combined_df.describe(include='all')

In [ ]:
combined_df.groupby(by="station").agg({
    "TEMP": ["max", "min"],
    "RAIN": ["max", "min"],
})

In [ ]:
combined_df.groupby(by="station").agg({
    "SO2": ["mean"],
    "NO2": ["mean"],
    "CO": ["mean"],
    "O3": ["mean"]
})

In [ ]:
# Rentang kategori untuk setiap polutan
category_ranges = ['Sehat', 'Sedang', 'Tidak sehat', 'Berbahaya']

pm25_ranges = [12, 35.4, 150.4, float('inf')]
pm10_ranges = [54, 154, 254, float('inf')]
so2_ranges = [35, 75, 185, float('inf')]
no2_ranges = [53, 100, 360, float('inf')]
co_ranges = [4400, 9400, 12400, float('inf')]
o3_ranges = [54, 70, 85, float('inf')]

# Fungsi untuk mengkategorikan polutan berdasarkan rentang
def categorize(value, ranges):
    for max_val in ranges:
        if value <= max_val:
            return ranges.index(max_val)

# Fungsi untuk menghitung kategori kualitas udara berdasarkan semua polutan
def categorize_air_quality(row):
    pm25_category = categorize(row['PM2.5'], pm25_ranges)
    pm10_category = categorize(row['PM10'], pm10_ranges)
    so2_category = categorize(row['SO2'], so2_ranges)
    no2_category = categorize(row['NO2'], no2_ranges)
    co_category = categorize(row['CO'], co_ranges)
    o3_category = categorize(row['O3'], o3_ranges)
    
    # Mengambil kategori tertinggi dari semua polutan (paling berbahaya)
    return max(pm25_category, pm10_category, so2_category, no2_category, co_category, o3_category)

# Menambahkan kolom 'Air Quality Category' ke DataFrame
combined_df['Air Quality Category'] = combined_df.apply(categorize_air_quality, axis=1)

# Mengonversi kategori menjadi nama kategori
combined_df['Air Quality Category'] = combined_df['Air Quality Category'].apply(lambda x: category_ranges[x])

# Menampilkan DataFrame dengan kategori kualitas udara
print(combined_df[['station', 'Air Quality Category']])

# Jika ingin melihat distribusi kategori kualitas udara di seluruh stasiun
category_counts = combined_df['Air Quality Category'].value_counts().sort_index()
print("Distribusi Kategori Kualitas Udara:")
print(category_counts)

**Insight:**
- Stasiun dengan curah hujan tertinggi yaitu Gucheng, 
- Jenis polutan tertinggi untuk setiap stasiun yaitu CO dan O3

## Visualization & Explanatory Analysis

### Pertanyaan 1: Bagaimana tren kualitas udara (PM2.5, PM10, SO2, NO2, CO, O3) di berbagai stasiun pengukuran sepanjang tahun?

In [ ]:
parameter_ranges = {
    'PM2.5': pm25_ranges,
    'PM10': pm10_ranges,
    'SO2': so2_ranges,
    'NO2': no2_ranges,
    'CO': co_ranges,
    'O3': o3_ranges,
}

# Visualisasi tren kualitas udara berdasarkan parameter di berbagai stasiun pengukuran
fig, axes = plt.subplots(nrows=2, ncols=3, figsize=(15, 10))
fig.suptitle('Tren Kualitas Udara Berdasarkan Parameter di Berbagai Stasiun Pengukuran', fontsize=16)

for ax, (param, ranges) in zip(axes.flatten(), parameter_ranges.items()):
    sns.lineplot(data=combined_df, x='year', y=param, hue='station', ax=ax)
    ax.set_title(f'Tren {param} di Berbagai Stasiun')
    ax.set_xlabel('Tahun')
    ax.set_ylabel(param)

plt.tight_layout(rect=[0, 0, 1, 0.96])
plt.show()

### Pertanyaan 2: Bagaimana hubungan antara kondisi cuaca (suhu, tekanan udara, kelembaban, hujan, arah dan kecepatan angin) dengan kualitas udara?

In [ ]:
weather_columns = ['TEMP', 'PRES', 'DEWP', 'RAIN', 'WSPM']
air_quality_columns = ['PM2.5', 'PM10', 'SO2', 'NO2', 'CO', 'O3']

correlation_matrix = combined_df[weather_columns + air_quality_columns].corr()

plt.figure(figsize=(7, 5))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=.5)
plt.title('Heatmap Korelasi antara Parameter Cuaca dan Kualitas Udara')
plt.show()

In [ ]:
### Pertanyaan 3: Bagaimana perbandingan kualitas udara antar stasiun pada waktu tertentu?

In [ ]:
start_year = 2015
end_year = 2017

air_quality_parameters = ['PM2.5', 'PM10', 'SO2', 'NO2', 'CO', 'O3']

station_names = [
    'Aotizhongxin', 'Changping', 'Dingling', 'Dongsi', 'Guanyuan', 'Gucheng', 
    'Huairou', 'Nongzhanguan', 'Shunyi', 'Tiantan', 'Wanliu', 'Wanshouxigong'
]

fig, axs = plt.subplots(nrows=2, ncols=3, figsize=(18, 10))
fig.suptitle(f'Perbandingan Kualitas Udara Antar Stasiun ({start_year}-{end_year})', fontsize=16)

for i, parameter in enumerate(air_quality_parameters):
    row = i // 3
    col = i % 3

    axs[row, col].set_title(parameter)
    
    for j, combined_df in enumerate(dataframes):
        filtered_data = combined_df[(combined_df['year'] >= start_year) & (combined_df['year'] <= end_year)]
        axs[row, col].bar(station_names[j], filtered_data[parameter].mean(), label=station_names[j])

    axs[row, col].set_xlabel('Stasiun')
    axs[row, col].set_ylabel('Rata-rata Kualitas Udara')
    axs[row, col].legend()

plt.tight_layout(rect=[0, 0, 1, 0.96])
plt.show()

In [ ]:
# Menyimpan DataFrame yang telah diolah ke dalam file CSV
combined_df.to_csv('data_air_quality.csv', index=False)

combined_df = pd.read_csv('data_air_quality.csv')
combined_df

**Insight:**
- xxx
- xxx

## Analisis Lanjutan (Opsional)

## Conclusion

- Bagaimana tren kualitas udara (PM2.5, PM10, SO2, NO2, CO, O3) di berbagai stasiun pengukuran sepanjang tahun? Berdasarkan hasil yang diperoleh terdapat peningkatan polusi PM2.5, PM10, SO2, NO2, CO dari tahun 2013 hingga 2017. Puncaknya pada tahun 2016 ke tahun 2017. Namun untuk O3 terjadi penurunan pada tahun 2016 ke tahun 2017.
- Bagaimana hubungan antara kondisi cuaca (suhu, tekanan udara, kelembaban, hujan, arah dan kecepatan angin) dengan kualitas udara? Parameter cuaca memiliki pengaruh yang signifikan terhadap kualitas udara. Suhu dan kelembaban udara memiliki korelasi positif yang kuat, yang berarti bahwa semakin tinggi suhu dan kelembaban udara, semakin tinggi pula konsentrasi PM2.5 dan PM10 di udara. Tekanan udara dan kecepatan angin memiliki korelasi negatif yang kuat, yang berarti bahwa semakin tinggi tekanan udara dan kecepatan angin, semakin rendah pula konsentrasi PM2.5 dan PM10 di udara. Curah hujan memiliki korelasi negatif yang lemah, yang berarti bahwa semakin tinggi curah hujan, semakin rendah pula konsentrasi PM2.5 dan PM10 di udara.
- Bagaimana perbandingan kualitas udara antar stasiun pada waktu 2015 hingga 2017? Rata-rata kualitas udara di semua stasiun adalah buruk. Stasiun dengan kualitas udara terburuk adalah Wanshouxigong, Shunyi, dan Tiantan, ketiga stasiun ini terletak di kota-kota besar. Sedangkan, stasiun dengan kualitas udara terbaik adalah Guanyuan, Gucheng, dan Huairou. Ketiga stasiun ini terletak di daerah pedesaan. Perbedaan yang cukup signifikan ini kemungkinan dipengaruhi oleh konsentrasi kendaraan bermotor yang lebih rendah, aktivitas industri yang lebih rendah dan pembakaran bahan bakar fosil yang lebih rendah.